---
title: "R Notebook"
output: html_notebook
---

```{r}
library(httr)
library(xml2)
library(rvest)
library(data.table)
library(dplyr)
library(tidyverse)
library(ggmap)
library(mapproj)
library(ggplot2)
library(readxl)
```

```{r}
url <- "http://blog.xuite.net/tcchian/travel/44752953"

MRT <- list()
doc <- read_html(url)
MRT[[7]] <- html_table(html_nodes(doc, "#content_all > table:nth-child(39)"), fill = TRUE)[[1]]

for(i in 1:7){
  MRT[[i]] <- MRT[[i]][-1,]
}
MRT.df <- rbindlist(MRT)

MRT.df <- MRT.df %>%
  select(X1, X2)

colnames(MRT.df) <- c("Line", "Station")

MRT.df$Station <- gsub("[A-Za-z0-9]+", "", MRT.df$Station)
MRT.df$Line <- gsub("[A-Za-z0-9]+", "", MRT.df$Line)

MRT1 <- MRT.df %>%
  filter(duplicated(Station) == T) 

colnames(MRT1)[1] <- "Line2"

MRT.df <- MRT.df %>%
  filter(duplicated(Station) == F)

MRT <- merge(MRT.df, MRT1, all.x = T)
MRT$Station <- paste0("捷運", MRT$Station)

write.csv(MRT, "MRT.csv")
```


```{r}
MRTlon <- read_excel("/Users/penny/Documents/GitHub/Rsummercode-Final-Project/data/MRTlon.xlsx")

MRTlon$Station <- paste0("捷運", MRTlon$Station)

MRT <- merge(MRT, MRTlon, all = T)
write.csv(MRT, "MRT.csv")
```

